android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m
# SDK_REGISTRY_TOKEN=sk.eyJ1IjoiZGV2dGVhbTIwMjQiLCJhIjoiY2x2Z2N2cDY1MHdhejJqcDUybmgxM3NlMiJ9.Jx8aGUObGnaGbJm_5z6YTA
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoiZGV2dGVhbTIwMjQiLCJhIjoiY2x2Z2N2cDY1MHdhejJqcDUybmgxM3NlMiJ9.Jx8aGUObGnaGbJm_5z6YTA
